### ISSUE TITLE
Prefer absolute references to Google Trillian?

### ISSUE THREAD

**Issue by DazWilkin** [google/keytransparency#1193]
Cloning your `keytransparency` repo to evaluate your PR #1191, I must also clone `trillian`. The `docker-compose.yaml` file in `keytransparency` makes relative references from itself to Trillian to source Dockerfiles.

Would it be 'better' to decouple this?
- Either (preferably?): Assume the existence of Docker images for the Trillian servers? IIRC Trillian was planning to publish Trillian server images publicly on build.
- Or: Make absolute references (`github.com/google/trillian`) to the Trillian Dockerfile sources.

**Comment by gdbelvin** [comment]
Here's the problem that the relative reference is trying to address: building a local docker image that reflects the state of one's own Go source tree for debugging.  Copying a relative local path is indeed a broken solution, trying to strike the right balance between copying the entire go repo into the docker image, vs just the parts that we expect to change. 

The underlying issue is that KT and Trillian don't have go modules turned on and without go modules anything short of copying the entire go source tree into the container is destined to be broken.  Perhaps this is a good use case for making process on adopting Go modules.

Ref: google/trillian#1400

**Comment by DazWilkin** [comment]
Right!

Yes, I'd not considered Modules. That would be possibly best.

Using Docker images as the "interface" also seems compelling. IIUC you're not needing to rebuild Trillian each time (it's not changing) so you could take a dependency on `:latest` for the Trillian images or some known-good version.

**Comment by gdbelvin** [comment]
Fixed by #1201  and #1389
