### ISSUE TITLE
Include Sequence Number in Mutations

### ISSUE THREAD

**Issue by gdbelvin** [google/keytransparency#487]
Certificate Transparency does not guarantee that items will be sequenced in the same order they are submitted. We can either provide our own definitive sequencing, or wait for the Trillian Log to sequence. In order to avoid taking on a new production performance dependency, let's provide our own ordering via our own sequence number before submitting to Trillian.  

- We might even be able to supply our own sequence number to Trillian. 
- Monitors will need to explicitly order by the provided sequence number rather than Trillian ordering.  @cesarghali

**Comment by cesarghali** [comment]
Although we discussed this offline and realized that we might not need sequence numbering here, I think we still need it to allow paging. Monitors might call the `GetMutations` API (or whatever we end up calling it) and request to get mutations in pages. There should be a way to index into the list of mutations in order to support paging.

**Comment by gdbelvin** [comment]
Sounds good. We can either page by mutation index or epoch.

**Comment by cesarghali** [comment]
Correct. This is what I have in mind for the API:

* Monitors call `GetMutations` in epoch `e` starting from the "beginning" of mutation index and with page size of `p`.
* Server returns the requested data and sets the next index to be "beginning" + `p`.

This is very similar to what we have in history. I am working now on adding sequence numbers to mutations.
