### ISSUE TITLE
Consistent index start

### ISSUE THREAD

**Issue by Liamsi** [google/keytransparency#703]
Provide a function (or several) in a central place that takes care of indices/revisions/numbers/epochs such that epochs can start at 0 without error'ing and without making the dev think about it in every single call.

**Comment by gdbelvin** [comment]
Related to #756

**Comment by gdbelvin** [comment]
Proposed solutions: 
- The `trillian.LogClient` that KT uses should wrap the necessary calls and provide a MapRevision based API that does the appropriate translation. 
- We could insert a proper `0` entry into the Log to get us started and make the map revision equal to the log index.  
  - No translation layer would be needed
  - Since the 0 entry is an empty struct, we could keep the current API which interprets requests for revision 0 as requests for the current epoch. 
   - Index 0 would be the object hash of an empty `SignedMapRoot` struct - a well known value. 
   - Index 1 would be the hash of the first signed map root of an empty map. 
   - Index 2 would be the first to location to contain user data.
