### ISSUE TITLE
Java Client

### ISSUE THREAD

**Issue by gdbelvin** [google/keytransparency#711]
Resources
- https://godoc.org/golang.org/x/mobile/cmd/gobind

**Comment by AMarcedone** [comment]
I am starting to look into using gobind. Maybe you tagged the wrong Antonio?

**Comment by gdbelvin** [comment]
Yep -- my bad. Thanks for taking this on!

**Comment by AMarcedone** [comment]
Update: I finally got an android studio project which leverages gobind to work (had to guess the right combination of gradle plugin versions that work together, as this is confusing and poorly documented).

However, the result is not really useful due to gobind's type restrictions: https://godoc.org/golang.org/x/mobile/cmd/gobind#hdr-Type_restrictions

I will briefly look into other similar alternatives and probably start a new Java implementation from scratch.

**Comment by gdbelvin** [comment]
It sounds like things might work if we created a verification API surface that was sufficiently simple? 
Could you start with the [Commitments](https://github.com/google/keytransparency/tree/master/core/crypto/commitments) package?

**Comment by AMarcedone** [comment]
I will try looking into that. My biggest concerns are how to handle logging (not sure how compatible the systems are) and the filesystem interface (I imagine I will have to use a Java interface for the android filesystem to read public key and cert files and then pass them as strings or byte arrays to the go part of the code).
Will keep you posted.

**Comment by AMarcedone** [comment]
Update: I wrote an interface for Commitments which correctly runs on my Android phone.

Next, I will look into extending the interface to other packages, as well as how to handle logging from go to android.

One issue I run into is that I cannot return protobuf generated structs to Java or use them directly as arguments in functional calls because gobind does not like the protobuf go code. I can serialize the protobufs to byte arrays to cross language boundaries. Not ideal, but it works.

**Comment by gdbelvin** [comment]
amazing!
I can put together some PRs to remove the dependency on protobuf in the
verification functions.
Logging -- I wonder if you could hook into the go logging interface and
pipe it out to the right Java logger?

**Comment by rmhrisk** [comment]
AWESOME

**Comment by AMarcedone** [comment]
Hey @gdbelvin, thanks a lot for the PRs. I will review them later today. 
In general, from now on I think it will be easier if I modify the go interfaces as I need to hook them up with the Java code I am writing. I will put you as a reviewer, if you do not mind :)
Stay tuned :)

**Comment by gdbelvin** [comment]
Sounds good.  :-)

**Comment by AMarcedone** [comment]
Update: Progress is good. 
I figured out how to hook into the logging interface as you suggested. 

A question I have is where to put the Android/Java part of the code I am writing. Should we create a directory in this repository or create another one?

**Comment by AMarcedone** [comment]
Update: I run into a very weird issue with gomobile/gobind, where the contents of some exported structs are sometimes overwritten with strange information without any reason. 
Might be a bug, but I am still investigating.

**Comment by AMarcedone** [comment]
I found a workaround for the problem I was having, but if you are curious here are more details:
https://stackoverflow.com/questions/45453775/gobind-generated-constructor-for-struct-containing-byte-sometimes-corrupts-dat

**Comment by AMarcedone** [comment]
![device-2017-08-02-170347](https://user-images.githubusercontent.com/9069413/28900261-cf53b586-77a4-11e7-871d-47d14cb38a1c.png)

RPC is working :) Little screenshot showing progress... This is interacting with the remote deployed kt server. The verification keys are not up to date so the failure of the various tests is expected.

**Comment by gdbelvin** [comment]
_Amazing_

**Comment by AMarcedone** [comment]
![ktandroidtest](https://user-images.githubusercontent.com/9069413/29435715-ed06602e-835c-11e7-8f48-3b493aefa7f2.png)
