### ISSUE TITLE
Monitor/Mutator: Cleanup handling of epoch 1

### ISSUE THREAD

**Issue by Liamsi** [google/keytransparency#811]
Currently, mutations can be requested for epochs starting from epoch 1. Epoch 1 is created initially by the sequencer if no previous epoch exists and the tree is still empty (no mutations exist).
The monitor currently needs to request epoch 1 which fails when inclusions proofs are setup to point the previous epoch which is the expected behavior (epoch 0 does not exist).

With 
https://github.com/google/keytransparency/blob/9b99af552b48b53c478217a6823cb17ecdbbbb68/core/mutation/mutation.go#L109-L115

we introduced a temporary workaround/hack that makes the API work even if epoch 1 (mutation do not exist) is requested. 

On the long-run we rather want:
- epoch 2 is the first epoch we want to allow the mutation service to allow as a valid request (mutations might exist)
- use/provide another API to request epoch 1

**Comment by gdbelvin** [comment]
This has been resolved in the following way: 

- During domain initialization, the first map root is placed in the trillian log so that log.tree_size should always >= 1.  
- Epoch == mapRoot.Revision.  Which starts at revision 0. 

#966 formalizes checking the latest revision during `GetLatestEpoch`
